In [2]:
import numpy as np

#  dimensions 
def creer_tableau(n, m):
    return np.random.randint(1, 10, size=(n, m))

# calcule la somme 
def somme(T):
    return np.sum(T, axis=1)

# calcule du produit 
def produit(T):
    return np.prod(T, axis=0)

# max
def maximum(T):
    return np.max(T, axis=1)

# min
def minimum(T):
    return np.min(T, axis=0)



In [3]:
 #run
n, m = 4, 5  
T = creer_tableau(n, m)
print("Tableau T :\n", T)

print("Somme des éléments de chaque ligne :", somme(T))
print("Produit des éléments de chaque colonne :", produit(T))
print("Valeur maximale de chaque ligne :", maximum(T))
print("Valeur minimale de chaque colonne :", minimum(T))

Tableau T :
 [[5 7 1 7 7]
 [5 7 2 6 2]
 [9 7 6 9 5]
 [8 8 2 7 7]]
Somme des éléments de chaque ligne : [27 22 36 32]
Produit des éléments de chaque colonne : [1800 2744   24 2646  490]
Valeur maximale de chaque ligne : [7 7 9 8]
Valeur minimale de chaque colonne : [5 7 1 6 2]


In [4]:
import random

# Fonction pour créer un tableau T de dimensions (n, m) avec des entiers aléatoires entre 1 et 9
def creer_tableau(n, m):
    T = [[random.randint(1, 9) for _ in range(m)] for _ in range(n)]
    return T

# Fonction pour calculer la somme des éléments de chaque ligne du tableau T
def somme(T):
    sommes = []
    for ligne in T:
        total = 0
        for element in ligne:
            total += element
        sommes.append(total)
    return sommes

# Fonction pour calculer le produit des éléments de chaque colonne du tableau T
def produit(T):
    produits = []
    nb_lignes = len(T)
    nb_colonnes = len(T[0]) if nb_lignes > 0 else 0
    for j in range(nb_colonnes):
        produit_colonne = 1
        for i in range(nb_lignes):
            produit_colonne *= T[i][j]
        produits.append(produit_colonne)
    return produits

# Fonction pour trouver la valeur maximale de chaque ligne du tableau T
def maximum(T):
    max_values = []
    for ligne in T:
        max_ligne = ligne[0]
        for element in ligne:
            if element > max_ligne:
                max_ligne = element
        max_values.append(max_ligne)
    return max_values

# Fonction pour trouver la valeur minimale de chaque colonne du tableau T
def minimum(T):
    min_values = []
    nb_lignes = len(T)
    nb_colonnes = len(T[0]) if nb_lignes > 0 else 0
    for j in range(nb_colonnes):
        min_colonne = T[0][j]
        for i in range(nb_lignes):
            if T[i][j] < min_colonne:
                min_colonne = T[i][j]
        min_values.append(min_colonne)
    return min_values

# Exécution de l'exemple
n, m = 4, 5  # Par exemple, un tableau de 4 lignes et 5 colonnes
T = creer_tableau(n, m)
print("Tableau T :")
for ligne in T:
    print(ligne)

print("Somme des éléments de chaque ligne :", somme(T))
print("Produit des éléments de chaque colonne :", produit(T))
print("Valeur maximale de chaque ligne :", maximum(T))
print("Valeur minimale de chaque colonne :", minimum(T))


Tableau T :
[7, 4, 2, 7, 1]
[2, 6, 5, 3, 6]
[9, 6, 8, 9, 3]
[2, 5, 9, 1, 5]
Somme des éléments de chaque ligne : [21, 22, 35, 22]
Produit des éléments de chaque colonne : [252, 720, 720, 189, 90]
Valeur maximale de chaque ligne : [7, 6, 9, 9]
Valeur minimale de chaque colonne : [2, 4, 2, 1, 1]
